#include "StaticData.h"
#include "port/ShipUtils.h"

#include "port/hooks/list/PlayerEvent.h"
#include "port/mods/PortEnhancements.h"

extern "C" {
#include "game/area.h"
}

namespace Rando {

namespace StaticData {
std::array<std::string, RC_MAX> CheckNames = std::array<std::string, RC_MAX>();

#define RC(id, type, level, act, item, x, y, z)      \
    {                                                \
        id, {                                        \
            id, #id, type, level, act, item, x, y, z \
        }                                            \
    }

// clang-format off
std::map<RandoCheckId, RandoStaticCheck> Checks = {
    RC(RC_UNKNOWN,                          RCTYPE_UNKNOWN,         LEVEL_UNKNOWN_1,    RA_ACT_NONE,    RI_UNKNOWN,     0, 0, 0),
    RC(RC_AQUA_RED_COIN_01,                 RCTYPE_COIN_RED,        LEVEL_SA,           RA_ACT_NONE,    RI_COIN_RED,    -2400, -4607, -2400),
    RC(RC_AQUA_RED_COIN_02,                 RCTYPE_COIN_RED,        LEVEL_SA,           RA_ACT_NONE,    RI_COIN_RED,    -2400, -4607, 2400),
    RC(RC_AQUA_RED_COIN_03,                 RCTYPE_COIN_RED,        LEVEL_SA,           RA_ACT_NONE,    RI_COIN_RED,    2400, -4607, 2400),
    RC(RC_AQUA_RED_COIN_04,                 RCTYPE_COIN_RED,        LEVEL_SA,           RA_ACT_NONE,    RI_COIN_RED,    2400, -4607, -2400),
    RC(RC_AQUA_RED_COIN_05,                 RCTYPE_COIN_RED,        LEVEL_SA,           RA_ACT_NONE,    RI_COIN_RED,    0, -2200, -1500),
    RC(RC_AQUA_RED_COIN_06,                 RCTYPE_COIN_RED,        LEVEL_SA,           RA_ACT_NONE,    RI_COIN_RED,    -1500, -2200, 0),
    RC(RC_AQUA_RED_COIN_07,                 RCTYPE_COIN_RED,        LEVEL_SA,           RA_ACT_NONE,    RI_COIN_RED,    0, -2200, 1500),
    RC(RC_AQUA_RED_COIN_08,                 RCTYPE_COIN_RED,        LEVEL_SA,           RA_ACT_NONE,    RI_COIN_RED,    1500, -2200, 0),
    RC(RC_AQUA_STAR_RED_COINS,              RCTYPE_STAR_RED_COIN,   LEVEL_SA,           RA_ACT_01,      RI_STAR,        0, -4250, 0),
    RC(RC_BBH_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_BLUE,   1400, 1840, 1100),
    RC(RC_BBH_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_BLUE,   1700, 1840, 1100),
    RC(RC_BBH_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_BLUE,   0, 1840, 1100),
    RC(RC_BBH_BLUE_COIN_04,                 RCTYPE_COIN_BLUE,       LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_BLUE,   -400, 1840, 1100),
    RC(RC_BBH_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_RED,    -1164, 0, 2325),
    RC(RC_BBH_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_RED,    2540, 820, 2174),
    RC(RC_BBH_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_RED,    2600, 815, -380),
    RC(RC_BBH_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_RED,    2950, 815, -1250),
    RC(RC_BBH_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_RED,    -1500, 550, 960),
    RC(RC_BBH_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_RED,    -420, 550, 60),
    RC(RC_BBH_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_RED,    2856, 50, 2144),
    RC(RC_BBH_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_BBH,          RA_ACT_NONE,    RI_COIN_RED,    50, 900, -1400),
    RC(RC_BBH_STAR_01_GHOST_HUNT,           RCTYPE_STAR_DEFAULT,    LEVEL_BBH,          RA_ACT_01,      RI_STAR,        980, 1100, 250),
    RC(RC_BBH_STAR_02_MERRY_GO_ROUND,       RCTYPE_STAR_DEFAULT,    LEVEL_BBH,          RA_ACT_02,      RI_STAR,        -1600, -2100, 205),
    RC(RC_BBH_STAR_03_HAUNTED_BOOKS,        RCTYPE_STAR_DEFAULT,    LEVEL_BBH,          RA_ACT_03,      RI_STAR,        -2030, 1350, 1940),
    RC(RC_BBH_STAR_04_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_BBH,          RA_ACT_04,      RI_STAR,        -204, 1100, 1576),
    RC(RC_BBH_STAR_05_BALCONY,              RCTYPE_STAR_DEFAULT,    LEVEL_BBH,          RA_ACT_05,      RI_STAR,        700, 3200, 1900),
    RC(RC_BBH_STAR_06_SECRET_ROOM,          RCTYPE_STAR_DEFAULT,    LEVEL_BBH,          RA_ACT_06,      RI_STAR,        1370, 2000, -320),
    RC(RC_BBH_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_BBH,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_BITDW_RED_COIN_01,                RCTYPE_COIN_RED,        LEVEL_BITDW,        RA_ACT_NONE,    RI_COIN_RED,    -3100, -2900, 4520),
    RC(RC_BITDW_RED_COIN_02,                RCTYPE_COIN_RED,        LEVEL_BITDW,        RA_ACT_NONE,    RI_COIN_RED,    -4740, 1050, -2130),
    RC(RC_BITDW_RED_COIN_03,                RCTYPE_COIN_RED,        LEVEL_BITDW,        RA_ACT_NONE,    RI_COIN_RED,    -3120, 1160, -2570),
    RC(RC_BITDW_RED_COIN_04,                RCTYPE_COIN_RED,        LEVEL_BITDW,        RA_ACT_NONE,    RI_COIN_RED,    -4613, 1220, -427),
    RC(RC_BITDW_RED_COIN_05,                RCTYPE_COIN_RED,        LEVEL_BITDW,        RA_ACT_NONE,    RI_COIN_RED,    -1000, 1933, 466),
    RC(RC_BITDW_RED_COIN_06,                RCTYPE_COIN_RED,        LEVEL_BITDW,        RA_ACT_NONE,    RI_COIN_RED,    -6475, 125, 890),
    RC(RC_BITDW_RED_COIN_07,                RCTYPE_COIN_RED,        LEVEL_BITDW,        RA_ACT_NONE,    RI_COIN_RED,    -7810, -3100, 4900),
    RC(RC_BITDW_RED_COIN_08,                RCTYPE_COIN_RED,        LEVEL_BITDW,        RA_ACT_NONE,    RI_COIN_RED,    1500, 1066, -166),
    RC(RC_BITDW_STAR_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_BITDW,        RA_ACT_01,      RI_STAR,        7180, 3000, 0),
    RC(RC_BITFS_RED_COIN_01,                RCTYPE_COIN_RED,        LEVEL_BITFS,        RA_ACT_NONE,    RI_COIN_RED,    2888, -1375, 310),
    RC(RC_BITFS_RED_COIN_02,                RCTYPE_COIN_RED,        LEVEL_BITFS,        RA_ACT_NONE,    RI_COIN_RED,    1230, -1900, -1747),
    RC(RC_BITFS_RED_COIN_03,                RCTYPE_COIN_RED,        LEVEL_BITFS,        RA_ACT_NONE,    RI_COIN_RED,    5800, -2000, 0),
    RC(RC_BITFS_RED_COIN_04,                RCTYPE_COIN_RED,        LEVEL_BITFS,        RA_ACT_NONE,    RI_COIN_RED,    -1846, 1600, -476),
    RC(RC_BITFS_RED_COIN_05,                RCTYPE_COIN_RED,        LEVEL_BITFS,        RA_ACT_NONE,    RI_COIN_RED,    -4210, 2615, 280),
    RC(RC_BITFS_RED_COIN_06,                RCTYPE_COIN_RED,        LEVEL_BITFS,        RA_ACT_NONE,    RI_COIN_RED,    -1390, 3575, -420),
    RC(RC_BITFS_RED_COIN_07,                RCTYPE_COIN_RED,        LEVEL_BITFS,        RA_ACT_NONE,    RI_COIN_RED,    3065, 4610, 92),
    RC(RC_BITFS_RED_COIN_08,                RCTYPE_COIN_RED,        LEVEL_BITFS,        RA_ACT_NONE,    RI_COIN_RED,    4330, -790, -50),
    RC(RC_BITFS_STAR_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_BITFS,        RA_ACT_01,      RI_STAR,        1200, 5700, 160),
    RC(RC_BITS_RED_COIN_01,                 RCTYPE_COIN_RED,        LEVEL_BITS,         RA_ACT_NONE,    RI_COIN_RED,    1590, -1120, -2055),
    RC(RC_BITS_RED_COIN_02,                 RCTYPE_COIN_RED,        LEVEL_BITS,         RA_ACT_NONE,    RI_COIN_RED,    -2960, -3360, 0),
    RC(RC_BITS_RED_COIN_03,                 RCTYPE_COIN_RED,        LEVEL_BITS,         RA_ACT_NONE,    RI_COIN_RED,    -298, -2600, -1600),
    RC(RC_BITS_RED_COIN_04,                 RCTYPE_COIN_RED,        LEVEL_BITS,         RA_ACT_NONE,    RI_COIN_RED,    7618, 4850, -1909),
    RC(RC_BITS_RED_COIN_05,                 RCTYPE_COIN_RED,        LEVEL_BITS,         RA_ACT_NONE,    RI_COIN_RED,    -136, 3109, -909),
    RC(RC_BITS_RED_COIN_06,                 RCTYPE_COIN_RED,        LEVEL_BITS,         RA_ACT_NONE,    RI_COIN_RED,    -3330, 4050, -900),
    RC(RC_BITS_RED_COIN_07,                 RCTYPE_COIN_RED,        LEVEL_BITS,         RA_ACT_NONE,    RI_COIN_RED,    -4830, 2103, -1030),
    RC(RC_BITS_RED_COIN_08,                 RCTYPE_COIN_RED,        LEVEL_BITS,         RA_ACT_NONE,    RI_COIN_RED,    348, 5921, -4585),
    RC(RC_BOB_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_BOB,          RA_ACT_NONE,    RI_COIN_RED,    -5500, 768, 2400),
    RC(RC_BOB_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_BOB,          RA_ACT_NONE,    RI_COIN_RED,    -6500, 768, 2400),
    RC(RC_BOB_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_BOB,          RA_ACT_NONE,    RI_COIN_RED,    1135, 1920, -7161),
    RC(RC_BOB_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_BOB,          RA_ACT_NONE,    RI_COIN_RED,    250, 1000, 1920),
    RC(RC_BOB_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_BOB,          RA_ACT_NONE,    RI_COIN_RED,    1600, 980, 4440),
    RC(RC_BOB_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_BOB,          RA_ACT_NONE,    RI_COIN_RED,    -2755, 0, -4083),
    RC(RC_BOB_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_BOB,          RA_ACT_NONE,    RI_COIN_RED,    4934, 1352, 861),
    RC(RC_BOB_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_BOB,          RA_ACT_NONE,    RI_COIN_RED,    4100, 3672, 1629),
    RC(RC_BOB_STAR_01_KING_BOBOMB,          RCTYPE_STAR_DEFAULT,    LEVEL_BOB,          RA_ACT_01,      RI_STAR,        2000, 4500, -4500),
    RC(RC_BOB_STAR_02_KOOPA_RACE,           RCTYPE_STAR_DEFAULT,    LEVEL_BOB,          RA_ACT_02,      RI_STAR,        3030, 4500, -4600),
    RC(RC_BOB_STAR_03_ISLAND,               RCTYPE_STAR_DEFAULT,    LEVEL_BOB,          RA_ACT_03,      RI_STAR,        5540, 3350, 1200),
    RC(RC_BOB_STAR_04_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_BOB,          RA_ACT_04,      RI_STAR,        -6000, 1000, 2400),
    RC(RC_BOB_STAR_05_WINGS,                RCTYPE_STAR_DEFAULT,    LEVEL_BOB,          RA_ACT_05,      RI_STAR,        -6600, 1000, 1250),
    RC(RC_BOB_STAR_06_CHAIN_CHOMP,          RCTYPE_STAR_DEFAULT,    LEVEL_BOB,          RA_ACT_06,      RI_STAR,        1550, 1200, 300),
    RC(RC_BOB_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_BOB,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_CASTLE_STAR_01_TOAD_BASEMENT,     RCTYPE_STAR_DEFAULT,    LEVEL_CASTLE,       RA_ACT_01,      RI_STAR,        1787, -1381, -1957),
    RC(RC_CASTLE_STAR_02_TOAD_2ND_FLOOR,    RCTYPE_STAR_DEFAULT,    LEVEL_CASTLE,       RA_ACT_02,      RI_STAR,        -977, 1203, 2569),
    RC(RC_CASTLE_STAR_03_TOAD_3RD_FLOOR,    RCTYPE_STAR_DEFAULT,    LEVEL_CASTLE,       RA_ACT_03,      RI_STAR,        -1584, 2253, 7157),
    RC(RC_CASTLE_STAR_04_MIPS_FIRST,        RCTYPE_STAR_DEFAULT,    LEVEL_CASTLE,       RA_ACT_04,      RI_STAR,        0, 0, 0),
    RC(RC_CASTLE_STAR_05_MIPS_SECOND,       RCTYPE_STAR_DEFAULT,    LEVEL_CASTLE,       RA_ACT_05,      RI_STAR,        0, 0, 1),
    RC(RC_CCM_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_BLUE,   3400, -640, -740),
    RC(RC_CCM_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_BLUE,   3400, -320, -1740),
    RC(RC_CCM_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_BLUE,   -3160, 6267, -6120),
    RC(RC_CCM_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_RED,    -488, 3100, -2305),
    RC(RC_CCM_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_RED,    -3120, -1200, -2080),
    RC(RC_CCM_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_RED,    2940, -1400, 2630),
    RC(RC_CCM_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_RED,    -600, -505, 1940),
    RC(RC_CCM_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_RED,    -3814, -2112, 6427),
    RC(RC_CCM_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_RED,    2700, -4600, 1230),
    RC(RC_CCM_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_RED,    1990, -4040, 4950),
    RC(RC_CCM_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_CCM,          RA_ACT_NONE,    RI_COIN_RED,    4408, -4550, -1534),
    RC(RC_CCM_STAR_01_SLIDING_AWAY,         RCTYPE_STAR_DEFAULT,    LEVEL_CCM,          RA_ACT_01,      RI_STAR,        2500, -4350, 5750),
    RC(RC_CCM_STAR_02_LOST_PENGUIN,         RCTYPE_STAR_DEFAULT,    LEVEL_CCM,          RA_ACT_02,      RI_STAR,        3167, -4300, 5108),
    RC(RC_CCM_STAR_03_PENGUIN_RACE,         RCTYPE_STAR_DEFAULT,    LEVEL_CCM,          RA_ACT_03,      RI_STAR,        -7339, -5700, -6774),
    RC(RC_CCM_STAR_04_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_CCM,          RA_ACT_04,      RI_STAR,        4200, -927, 400),
    RC(RC_CCM_STAR_05_LOST_HEAD,            RCTYPE_STAR_DEFAULT,    LEVEL_CCM,          RA_ACT_05,      RI_STAR,        -4700, -1024, 1890),
    RC(RC_CCM_STAR_06_WALL_KICKS,           RCTYPE_STAR_DEFAULT,    LEVEL_CCM,          RA_ACT_06,      RI_STAR,        -2000, -2200, -3000),
    RC(RC_CCM_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_CCM,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_COTMC_RED_COIN_01,                RCTYPE_COIN_RED,        LEVEL_COTMC,        RA_ACT_NONE,    RI_COIN_RED,    200, -291, -5600),
    RC(RC_COTMC_RED_COIN_02,                RCTYPE_COIN_RED,        LEVEL_COTMC,        RA_ACT_NONE,    RI_COIN_RED,    980, 260, -3430),
    RC(RC_COTMC_RED_COIN_03,                RCTYPE_COIN_RED,        LEVEL_COTMC,        RA_ACT_NONE,    RI_COIN_RED,    -540, -352, -5940),
    RC(RC_COTMC_RED_COIN_04,                RCTYPE_COIN_RED,        LEVEL_COTMC,        RA_ACT_NONE,    RI_COIN_RED,    -300, 450, -6240),
    RC(RC_COTMC_RED_COIN_05,                RCTYPE_COIN_RED,        LEVEL_COTMC,        RA_ACT_NONE,    RI_COIN_RED,    -200, -400, -6680),
    RC(RC_COTMC_RED_COIN_06,                RCTYPE_COIN_RED,        LEVEL_COTMC,        RA_ACT_NONE,    RI_COIN_RED,    250, 450, -6400),
    RC(RC_COTMC_RED_COIN_07,                RCTYPE_COIN_RED,        LEVEL_COTMC,        RA_ACT_NONE,    RI_COIN_RED,    540, -361, -6340),
    RC(RC_COTMC_RED_COIN_08,                RCTYPE_COIN_RED,        LEVEL_COTMC,        RA_ACT_NONE,    RI_COIN_RED,    980, 260, -3810),
    RC(RC_COTMC_STAR_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_COTMC,        RA_ACT_01,      RI_STAR,        0, -200, -7000),
    RC(RC_DDD_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_BLUE,   1414, 1020, 622),
    RC(RC_DDD_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_BLUE,   1814, 1020, 622),
    RC(RC_DDD_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_BLUE,   1814, 1020, 1222),
    RC(RC_DDD_BLUE_COIN_04,                 RCTYPE_COIN_BLUE,       LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_BLUE,   1414, 1020, 1222),
    RC(RC_DDD_BLUE_COIN_05,                 RCTYPE_COIN_BLUE,       LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_BLUE,   1414, 1020, 922),
    RC(RC_DDD_BLUE_COIN_06,                 RCTYPE_COIN_BLUE,       LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_BLUE,   1814, 1020, 922),
    RC(RC_DDD_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_RED,    4680, 1155, -2200),
    RC(RC_DDD_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_RED,    3525, 1155, -2250),
    RC(RC_DDD_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_RED,    3850, 1111, 3550),
    RC(RC_DDD_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_RED,    4400, 1288, 3595),
    RC(RC_DDD_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_RED,    2974, 1015, 3584),
    RC(RC_DDD_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_RED,    5550, 1015, 3575),
    RC(RC_DDD_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_RED,    3300, 1111, -1900),
    RC(RC_DDD_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_DDD,          RA_ACT_NONE,    RI_COIN_RED,    2100, 1025, -1600),
    RC(RC_DDD_STAR_01_BOWSERS_SUB,          RCTYPE_STAR_DEFAULT,    LEVEL_DDD,          RA_ACT_01,      RI_STAR,        3900, 850, -600),
    RC(RC_DDD_STAR_02_CHESTS,               RCTYPE_STAR_DEFAULT,    LEVEL_DDD,          RA_ACT_02,      RI_STAR,        -1900, -4000, -1400),
    RC(RC_DDD_STAR_03_RED_COINS,            RCTYPE_STAR_DEFAULT,    LEVEL_DDD,          RA_ACT_03,      RI_STAR,        5513, 1200, 900),
    RC(RC_DDD_STAR_04_JET_STREAM,           RCTYPE_STAR_RED_COIN,   LEVEL_DDD,          RA_ACT_04,      RI_STAR,        3400, -3200, -500),
    RC(RC_DDD_STAR_05_MANTA_RAY,            RCTYPE_STAR_DEFAULT,    LEVEL_DDD,          RA_ACT_05,      RI_STAR,        -3180, -3600, 120),
    RC(RC_DDD_STAR_06_CAPS,                 RCTYPE_STAR_DEFAULT,    LEVEL_DDD,          RA_ACT_06,      RI_STAR,        2030, -3700, -2780),
    RC(RC_DDD_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_DDD,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_HMC_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_BLUE,   3945, -1023, -2918),
    RC(RC_HMC_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_BLUE,   3800, -1023, -4009),
    RC(RC_HMC_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_BLUE,   3036, -858, -4118),
    RC(RC_HMC_BLUE_COIN_04,                 RCTYPE_COIN_BLUE,       LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_BLUE,   2018, -921, -4154),
    RC(RC_HMC_BLUE_COIN_05,                 RCTYPE_COIN_BLUE,       LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_BLUE,   1836, -921, -4700),
    RC(RC_HMC_BLUE_COIN_06,                 RCTYPE_COIN_BLUE,       LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_BLUE,   1836, -721, -4700),
    RC(RC_HMC_BLUE_COIN_07,                 RCTYPE_COIN_BLUE,       LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_BLUE,   1836, -521, -4700),
    RC(RC_HMC_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_RED,    2140, 2048, 6540),
    RC(RC_HMC_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_RED,    2900, 2048, 6500),
    RC(RC_HMC_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_RED,    6400, 2090, 5320),
    RC(RC_HMC_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_RED,    6820, 1024, 3300),
    RC(RC_HMC_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_RED,    6260, 1124, 4960),
    RC(RC_HMC_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_RED,    4080, 1124, 5760),
    RC(RC_HMC_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_RED,    4640, 2250, 3980),
    RC(RC_HMC_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_HMC,          RA_ACT_NONE,    RI_COIN_RED,    2960, 1124, 5140),
    RC(RC_HMC_STAR_01_BEAST,                RCTYPE_STAR_DEFAULT,    LEVEL_HMC,          RA_ACT_01,      RI_STAR,        -3600, -4000, 3600),
    RC(RC_HMC_STAR_02_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_HMC,          RA_ACT_02,      RI_STAR,        4000, 300, 5000),
    RC(RC_HMC_STAR_03_METAL_HEAD,           RCTYPE_STAR_DEFAULT,    LEVEL_HMC,          RA_ACT_03,      RI_STAR,        6200, -4400, 2300),
    RC(RC_HMC_STAR_04_TOXIC_MAZE,           RCTYPE_STAR_DEFAULT,    LEVEL_HMC,          RA_ACT_04,      RI_STAR,        -2100, 2100, -7550),
    RC(RC_HMC_STAR_05_EMERGENCY_EXIT,       RCTYPE_STAR_DEFAULT,    LEVEL_HMC,          RA_ACT_05,      RI_STAR,        -6500, 2700, -1600),
    RC(RC_HMC_STAR_06_ROLLING_ROCKS,        RCTYPE_STAR_DEFAULT,    LEVEL_HMC,          RA_ACT_06,      RI_STAR,        -5000, 3050, -6700),
    RC(RC_HMC_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_HMC,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_JRB_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_BLUE,   5900, -2966, -7347),
    RC(RC_JRB_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_BLUE,   5300, -2966, -7347),
    RC(RC_JRB_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_BLUE,   4700, -2966, -7347),
    RC(RC_JRB_BLUE_COIN_04,                 RCTYPE_COIN_BLUE,       LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_BLUE,   4100, -2966, -7347),
    RC(RC_JRB_BLUE_COIN_05,                 RCTYPE_COIN_BLUE,       LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_BLUE,   3500, -2966, -7347),
    RC(RC_JRB_BLUE_COIN_06,                 RCTYPE_COIN_BLUE,       LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_BLUE,   2900, -2966, -7347),
    RC(RC_JRB_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_RED,    4900, 1800, 4700),
    RC(RC_JRB_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_RED,    -2535, 2110, 6113),
    RC(RC_JRB_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_RED,    -1845, -1003, 3518),
    RC(RC_JRB_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_RED,    -546, 530, 5930),
    RC(RC_JRB_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_RED,    648, -490, 4256),
    RC(RC_JRB_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_RED,    3642, -5103, 3175),
    RC(RC_JRB_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_RED,    4400, 2200, 1300),
    RC(RC_JRB_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_JRB,          RA_ACT_NONE,    RI_COIN_RED,    5400, 2200, 1300),
    RC(RC_JRB_STAR_01_SUNKEN_SHIP,          RCTYPE_STAR_DEFAULT,    LEVEL_JRB,          RA_ACT_01,      RI_STAR,        0, 1600, 3000),
    RC(RC_JRB_STAR_02_EEL,                  RCTYPE_STAR_DEFAULT,    LEVEL_JRB,          RA_ACT_02,      RI_STAR,        6833, -3654, 2230),
    RC(RC_JRB_STAR_03_OCEAN_CAVE,           RCTYPE_STAR_DEFAULT,    LEVEL_JRB,          RA_ACT_03,      RI_STAR,        -1800, -2500, -1700),
    RC(RC_JRB_STAR_04_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_JRB,          RA_ACT_04,      RI_STAR,        4900, 2400, 800),
    RC(RC_JRB_STAR_05_STONE_PILLAR,         RCTYPE_STAR_DEFAULT,    LEVEL_JRB,          RA_ACT_05,      RI_STAR,        1540, 2160, 2130),
    RC(RC_JRB_STAR_06_JET_STREAM,           RCTYPE_STAR_DEFAULT,    LEVEL_JRB,          RA_ACT_06,      RI_STAR,        5000, -4800, 2500),
    RC(RC_JRB_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_JRB,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_LLL_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_LLL,          RA_ACT_NONE,    RI_COIN_RED,    -5800, 220, 250),
    RC(RC_LLL_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_LLL,          RA_ACT_NONE,    RI_COIN_RED,    -5100, 220, 250),
    RC(RC_LLL_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_LLL,          RA_ACT_NONE,    RI_COIN_RED,    -5100, 220, 1000),
    RC(RC_LLL_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_LLL,          RA_ACT_NONE,    RI_COIN_RED,    -4400, 220, 1000),
    RC(RC_LLL_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_LLL,          RA_ACT_NONE,    RI_COIN_RED,    -4400, 220, 1750),
    RC(RC_LLL_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_LLL,          RA_ACT_NONE,    RI_COIN_RED,    -5100, 220, 1750),
    RC(RC_LLL_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_LLL,          RA_ACT_NONE,    RI_COIN_RED,    -5800, 220, 1750),
    RC(RC_LLL_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_LLL,          RA_ACT_NONE,    RI_COIN_RED,    -5800, 220, 1000),
    RC(RC_LLL_STAR_01_BIG_BULLY,            RCTYPE_STAR_DEFAULT,    LEVEL_LLL,          RA_ACT_01,      RI_STAR,        0, 950, -6800),
    RC(RC_LLL_STAR_02_LITTLE_BULLIES,       RCTYPE_STAR_DEFAULT,    LEVEL_LLL,          RA_ACT_02,      RI_STAR,        3700, 600, -5500),
    RC(RC_LLL_STAR_03_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_LLL,          RA_ACT_03,      RI_STAR,        -4400, 350, 250),
    RC(RC_LLL_STAR_04_LOG_ROLLING,          RCTYPE_STAR_DEFAULT,    LEVEL_LLL,          RA_ACT_04,      RI_STAR,        3100, 400, 7900),
    RC(RC_LLL_STAR_05_VOLCANO_FOOT,         RCTYPE_STAR_DEFAULT,    LEVEL_LLL,          RA_ACT_05,      RI_STAR,        2523, 3850, -901),
    RC(RC_LLL_STAR_06_VOLCANO_ELEVATOR,     RCTYPE_STAR_DEFAULT,    LEVEL_LLL,          RA_ACT_06,      RI_STAR,        1800, 3400, 1450),
    RC(RC_LLL_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_LLL,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_PSS_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_PSS,          RA_ACT_NONE,    RI_COIN_BLUE,   780, 5613, -5600),
    RC(RC_PSS_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_PSS,          RA_ACT_NONE,    RI_COIN_BLUE,   2360, 5979, -5600),
    RC(RC_PSS_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_PSS,          RA_ACT_NONE,    RI_COIN_BLUE,   -809, 5245, -5600),
    RC(RC_PSS_BLUE_COIN_04,                 RCTYPE_COIN_BLUE,       LEVEL_PSS,          RA_ACT_NONE,    RI_COIN_BLUE,   -2409, 4877, -5600),
    RC(RC_PSS_BLUE_COIN_05,                 RCTYPE_COIN_BLUE,       LEVEL_PSS,          RA_ACT_NONE,    RI_COIN_BLUE,   -4445, 4490, -5536),
    RC(RC_PSS_BLUE_COIN_06,                 RCTYPE_COIN_BLUE,       LEVEL_PSS,          RA_ACT_NONE,    RI_COIN_BLUE,   -6263, 4150, -4009),
    RC(RC_PSS_STAR_01_BOX,                  RCTYPE_STAR_DEFAULT,    LEVEL_PSS,          RA_ACT_01,      RI_STAR,        -6385, -4200, 5770),
    RC(RC_PSS_STAR_02_SPEED_TIME,           RCTYPE_STAR_DEFAULT,    LEVEL_PSS,          RA_ACT_02,      RI_STAR,        -6358, -4300, 4700),
    RC(RC_RR_BLUE_COIN_01,                  RCTYPE_COIN_BLUE,       LEVEL_RR,           RA_ACT_NONE,    RI_COIN_BLUE,   -6500, 1700, 0),
    RC(RC_RR_BLUE_COIN_02,                  RCTYPE_COIN_BLUE,       LEVEL_RR,           RA_ACT_NONE,    RI_COIN_BLUE,   -6200, 1700, 0),
    RC(RC_RR_BLUE_COIN_03,                  RCTYPE_COIN_BLUE,       LEVEL_RR,           RA_ACT_NONE,    RI_COIN_BLUE,   -5900, 1700, 0),
    RC(RC_RR_BLUE_COIN_04,                  RCTYPE_COIN_BLUE,       LEVEL_RR,           RA_ACT_NONE,    RI_COIN_BLUE,   -5600, 1700, 0),
    RC(RC_RR_BLUE_COIN_05,                  RCTYPE_COIN_BLUE,       LEVEL_RR,           RA_ACT_NONE,    RI_COIN_BLUE,   -6750, -1495, 0),
    RC(RC_RR_BLUE_COIN_06,                  RCTYPE_COIN_BLUE,       LEVEL_RR,           RA_ACT_NONE,    RI_COIN_BLUE,   -5300, 1700, 0),
    RC(RC_RR_RED_COIN_01,                   RCTYPE_COIN_RED,        LEVEL_RR,           RA_ACT_NONE,    RI_COIN_RED,    -5850, -1000, -50),
    RC(RC_RR_RED_COIN_02,                   RCTYPE_COIN_RED,        LEVEL_RR,           RA_ACT_NONE,    RI_COIN_RED,    -2950, -190, -50),
    RC(RC_RR_RED_COIN_03,                   RCTYPE_COIN_RED,        LEVEL_RR,           RA_ACT_NONE,    RI_COIN_RED,    -5850, 1150, 50),
    RC(RC_RR_RED_COIN_04,                   RCTYPE_COIN_RED,        LEVEL_RR,           RA_ACT_NONE,    RI_COIN_RED,    -5050, 800, -50),
    RC(RC_RR_RED_COIN_05,                   RCTYPE_COIN_RED,        LEVEL_RR,           RA_ACT_NONE,    RI_COIN_RED,    -4550, 650, -50),
    RC(RC_RR_RED_COIN_06,                   RCTYPE_COIN_RED,        LEVEL_RR,           RA_ACT_NONE,    RI_COIN_RED,    -5300, 200, -50),
    RC(RC_RR_RED_COIN_07,                   RCTYPE_COIN_RED,        LEVEL_RR,           RA_ACT_NONE,    RI_COIN_RED,    -3550, 1000, -50),
    RC(RC_RR_RED_COIN_08,                   RCTYPE_COIN_RED,        LEVEL_RR,           RA_ACT_NONE,    RI_COIN_RED,    -5800, -400, -50),
    RC(RC_RR_STAR_01_CRUISER,               RCTYPE_STAR_DEFAULT,    LEVEL_RR,           RA_ACT_01,      RI_STAR,        1450, 3400, -2352),
    RC(RC_RR_STAR_02_BIG_HOUSE,             RCTYPE_STAR_DEFAULT,    LEVEL_RR,           RA_ACT_02,      RI_STAR,        -4200, 6700, -4450),
    RC(RC_RR_STAR_03_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_RR,           RA_ACT_03,      RI_STAR,        -5150, -1400, 0),
    RC(RC_RR_STAR_04_SWINGIN_BREEZE,        RCTYPE_STAR_DEFAULT,    LEVEL_RR,           RA_ACT_04,      RI_STAR,        -5850, -700, 4950),
    RC(RC_RR_STAR_05_TRIANGLES,             RCTYPE_STAR_DEFAULT,    LEVEL_RR,           RA_ACT_05,      RI_STAR,        3700, -400, 6600),
    RC(RC_RR_STAR_06_OVER_THE_RAINBOW,      RCTYPE_STAR_DEFAULT,    LEVEL_RR,           RA_ACT_06,      RI_STAR,        5000, 4100, 4440),
    RC(RC_RR_STAR_07_100_COIN,              RCTYPE_STAR_DEFAULT,    LEVEL_RR,           RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_SL_RED_COIN_01,                   RCTYPE_COIN_RED,        LEVEL_SL,           RA_ACT_NONE,    RI_COIN_RED,    4750, 1061, -5230),
    RC(RC_SL_RED_COIN_02,                   RCTYPE_COIN_RED,        LEVEL_SL,           RA_ACT_NONE,    RI_COIN_RED,    416, 1050, -4522),
    RC(RC_SL_RED_COIN_03,                   RCTYPE_COIN_RED,        LEVEL_SL,           RA_ACT_NONE,    RI_COIN_RED,    -6560, 2040, -5080),
    RC(RC_SL_RED_COIN_04,                   RCTYPE_COIN_RED,        LEVEL_SL,           RA_ACT_NONE,    RI_COIN_RED,    -6760, 2040, -1360),
    RC(RC_SL_RED_COIN_05,                   RCTYPE_COIN_RED,        LEVEL_SL,           RA_ACT_NONE,    RI_COIN_RED,    -6880, 1857, 1000),
    RC(RC_SL_RED_COIN_06,                   RCTYPE_COIN_RED,        LEVEL_SL,           RA_ACT_NONE,    RI_COIN_RED,    -4211, 1092, -4723),
    RC(RC_SL_RED_COIN_07,                   RCTYPE_COIN_RED,        LEVEL_SL,           RA_ACT_NONE,    RI_COIN_RED,    -6271, 1390, 4764),
    RC(RC_SL_RED_COIN_08,                   RCTYPE_COIN_RED,        LEVEL_SL,           RA_ACT_NONE,    RI_COIN_RED,    -529, 1050, -5329),
    RC(RC_SL_STAR_01_BIG_HEAD,              RCTYPE_STAR_DEFAULT,    LEVEL_SL,           RA_ACT_01,      RI_STAR,        700, 4500, 690),
    RC(RC_SL_STAR_02_BULLY,                 RCTYPE_STAR_DEFAULT,    LEVEL_SL,           RA_ACT_02,      RI_STAR,        130, 1600, -4335),
    RC(RC_SL_STAR_03_DEEP_FREEZE,           RCTYPE_STAR_DEFAULT,    LEVEL_SL,           RA_ACT_03,      RI_STAR,        4350, 1350, 4350),
    RC(RC_SL_STAR_04_FREEZING_POND,         RCTYPE_STAR_DEFAULT,    LEVEL_SL,           RA_ACT_04,      RI_STAR,        -4700, 1300, 5850),
    RC(RC_SL_STAR_05_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_SL,           RA_ACT_05,      RI_STAR,        5000, 1200, 0),
    RC(RC_SL_STAR_06_IGLOO,                 RCTYPE_STAR_DEFAULT,    LEVEL_SL,           RA_ACT_06,      RI_STAR,        0, 500, 1000),
    RC(RC_SL_STAR_07_100_COIN,              RCTYPE_STAR_DEFAULT,    LEVEL_SL,           RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_SSL_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_BLUE,   0, 0, 2381),
    RC(RC_SSL_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_BLUE,   0, 100, 2381),
    RC(RC_SSL_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_BLUE,   0, 200, 2381),
    RC(RC_SSL_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_RED,    -4500, 1500, -3500),
    RC(RC_SSL_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_RED,    -4500, 1500, 1500),
    RC(RC_SSL_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_RED,    500, 1500, -3500),
    RC(RC_SSL_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_RED,    500, 1500, 1500),
    RC(RC_SSL_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_RED,    3380, 10, -4900),
    RC(RC_SSL_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_RED,    -5270, -170, -6780),
    RC(RC_SSL_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_RED,    -7450, 10, 7560),
    RC(RC_SSL_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_NONE,    RI_COIN_RED,    5900, 70, 2311),
    RC(RC_SSL_STAR_01_BIG_BIRD,             RCTYPE_STAR_DEFAULT,    LEVEL_SSL,          RA_ACT_01,      RI_STAR,        -5550, 300, -930),
    RC(RC_SSL_STAR_02_PYRAMID_TOP,          RCTYPE_STAR_DEFAULT,    LEVEL_SSL,          RA_ACT_02,      RI_STAR,        -2050, 1200, -580),
    RC(RC_SSL_STAR_03_PYRAMID_INSIDE,       RCTYPE_STAR_DEFAULT,    LEVEL_SSL,          RA_ACT_03,      RI_STAR,        500, 5050, -500),
    RC(RC_SSL_STAR_04_FOUR_PILLARS,         RCTYPE_STAR_DEFAULT,    LEVEL_SSL,          RA_ACT_04,      RI_STAR,        0, -900, -3700),
    RC(RC_SSL_STAR_05_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_SSL,          RA_ACT_05,      RI_STAR,        6000, 800, 3500),
    RC(RC_SSL_STAR_06_PYRAMID_PUZZLE,       RCTYPE_STAR_DEFAULT,    LEVEL_SSL,          RA_ACT_06,      RI_STAR,        900, 1400, 2350),
    RC(RC_SSL_STAR_07_100_COIN,             RCTYPE_COIN_RED,        LEVEL_SSL,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_THI_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_THI,          RA_ACT_NONE,    RI_COIN_BLUE,   -540, 1500, 1240),
    RC(RC_THI_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_THI,          RA_ACT_NONE,    RI_COIN_BLUE,   -840, 1500, 1440),
    RC(RC_THI_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_THI,          RA_ACT_NONE,    RI_COIN_RED,    1038, 1122, 998),
    RC(RC_THI_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_THI,          RA_ACT_NONE,    RI_COIN_RED,    1590, 1078, 160),
    RC(RC_THI_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_THI,          RA_ACT_NONE,    RI_COIN_RED,    1038, 1112, -823),
    RC(RC_THI_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_THI,          RA_ACT_NONE,    RI_COIN_RED,    -238, 1122, -1319),
    RC(RC_THI_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_THI,          RA_ACT_NONE,    RI_COIN_RED,    -523, 824, -500),
    RC(RC_THI_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_THI,          RA_ACT_NONE,    RI_COIN_RED,    -1838, 1068, 338),
    RC(RC_THI_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_THI,          RA_ACT_NONE,    RI_COIN_RED,    -240, 1500, 1040),
    RC(RC_THI_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_THI,          RA_ACT_NONE,    RI_COIN_RED,    -1914, 1360, -1909),
    RC(RC_THI_STAR_01_PIRANHA,              RCTYPE_STAR_DEFAULT,    LEVEL_THI,          RA_ACT_01,      RI_STAR,        -6300, -1850, -6300),
    RC(RC_THI_STAR_02_ISLAND_TOP,           RCTYPE_STAR_DEFAULT,    LEVEL_THI,          RA_ACT_02,      RI_STAR,        2600, 3500, -2400),
    RC(RC_THI_STAR_03_KOOPA_REMATCH,        RCTYPE_STAR_DEFAULT,    LEVEL_THI,          RA_ACT_03,      RI_STAR,        7100, -1300, -6000),
    RC(RC_THI_STAR_04_SECRETS,              RCTYPE_STAR_DEFAULT,    LEVEL_THI,          RA_ACT_04,      RI_STAR,        0, -700, -4500),
    RC(RC_THI_STAR_05_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_THI,          RA_ACT_05,      RI_STAR,        -1800, 800, -1500),
    RC(RC_THI_STAR_06_WIGGLER,              RCTYPE_STAR_DEFAULT,    LEVEL_THI,          RA_ACT_06,      RI_STAR,        0, 2048, 0),
    RC(RC_THI_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_THI,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_TOTWC_RED_COIN_01,                RCTYPE_COIN_RED,        LEVEL_TOTWC,        RA_ACT_NONE,    RI_COIN_RED,    -100, 800, -4000),
    RC(RC_TOTWC_RED_COIN_02,                RCTYPE_COIN_RED,        LEVEL_TOTWC,        RA_ACT_NONE,    RI_COIN_RED,    -3500, 0, 100),
    RC(RC_TOTWC_RED_COIN_03,                RCTYPE_COIN_RED,        LEVEL_TOTWC,        RA_ACT_NONE,    RI_COIN_RED,    100, -800, 3000),
    RC(RC_TOTWC_RED_COIN_04,                RCTYPE_COIN_RED,        LEVEL_TOTWC,        RA_ACT_NONE,    RI_COIN_RED,    4500, 1600, -100),
    RC(RC_TOTWC_RED_COIN_05,                RCTYPE_COIN_RED,        LEVEL_TOTWC,        RA_ACT_NONE,    RI_COIN_RED,    100, 800, -4000),
    RC(RC_TOTWC_RED_COIN_06,                RCTYPE_COIN_RED,        LEVEL_TOTWC,        RA_ACT_NONE,    RI_COIN_RED,    -3500, 0, -100),
    RC(RC_TOTWC_RED_COIN_07,                RCTYPE_COIN_RED,        LEVEL_TOTWC,        RA_ACT_NONE,    RI_COIN_RED,    -100, -800, 3000),
    RC(RC_TOTWC_RED_COIN_08,                RCTYPE_COIN_RED,        LEVEL_TOTWC,        RA_ACT_NONE,    RI_COIN_RED,    4500, 1600, 100),
    RC(RC_TOTWC_STAR_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_TOTWC,        RA_ACT_01,      RI_STAR,        800, -1700, 0),
    RC(RC_TTC_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_BLUE,   0, 20, -1400),
    RC(RC_TTC_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_BLUE,   -250, 20, -1700),
    RC(RC_TTC_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_BLUE,   250, 20, -1700),
    RC(RC_TTC_BLUE_COIN_04,                 RCTYPE_COIN_BLUE,       LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_BLUE,   0, 20, -2000),
    RC(RC_TTC_BLUE_COIN_05,                 RCTYPE_COIN_BLUE,       LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_BLUE,   500, 20, -2000),
    RC(RC_TTC_BLUE_COIN_06,                 RCTYPE_COIN_BLUE,       LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_BLUE,   -500, 20, -2000),
    RC(RC_TTC_BLUE_COIN_07,                 RCTYPE_COIN_BLUE,       LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_BLUE,   0, 20, -1700),
    RC(RC_TTC_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_RED,    800, -4400, 1900),
    RC(RC_TTC_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_RED,    800, -3700, 1900),
    RC(RC_TTC_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_RED,    800, -3000, 1900),
    RC(RC_TTC_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_RED,    1780, -3300, 1000),
    RC(RC_TTC_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_RED,    1388, -3300, 1428),
    RC(RC_TTC_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_RED,    200, -3000, 2000),
    RC(RC_TTC_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_RED,    200, -3700, 2000),
    RC(RC_TTC_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_TTC,          RA_ACT_NONE,    RI_COIN_RED,    200, -4400, 2000),
    RC(RC_TTC_STAR_01_CAGE,                 RCTYPE_STAR_DEFAULT,    LEVEL_TTC,          RA_ACT_01,      RI_STAR,        -1450, -1130, -1050),
    RC(RC_TTC_STAR_02_PENDULUMS,            RCTYPE_STAR_DEFAULT,    LEVEL_TTC,          RA_ACT_02,      RI_STAR,        -1850, 300, -950),
    RC(RC_TTC_STAR_03_HAND,                 RCTYPE_STAR_DEFAULT,    LEVEL_TTC,          RA_ACT_03,      RI_STAR,        -1300, -2250, -1300),
    RC(RC_TTC_STAR_04_THWOMP,               RCTYPE_STAR_DEFAULT,    LEVEL_TTC,          RA_ACT_04,      RI_STAR,        2200, 7300, 2210),
    RC(RC_TTC_STAR_05_MOVING_BARS,          RCTYPE_STAR_DEFAULT,    LEVEL_TTC,          RA_ACT_05,      RI_STAR,        -1050, 2400, -790),
    RC(RC_TTC_STAR_06_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_TTC,          RA_ACT_06,      RI_STAR,        1815, -3200, 800),
    RC(RC_TTC_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_TTC,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_TTM_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_NONE,    RI_COIN_RED,    1450, -2750, -4250),
    RC(RC_TTM_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_NONE,    RI_COIN_RED,    2550, -2750, -3400),
    RC(RC_TTM_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_NONE,    RI_COIN_RED,    4150, -2700, -2800),
    RC(RC_TTM_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_NONE,    RI_COIN_RED,    -1600, -1650, -2500),
    RC(RC_TTM_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_NONE,    RI_COIN_RED,    -1200, -1600, -3250),
    RC(RC_TTM_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_NONE,    RI_COIN_RED,    -1850, 100, -2850),
    RC(RC_TTM_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_NONE,    RI_COIN_RED,    -1500, -800, -2750),
    RC(RC_TTM_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_NONE,    RI_COIN_RED,    1840, -2880, -3600),
    RC(RC_TTM_STAR_01_MOUNTAIN_SCALE,       RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_01,      RI_STAR,        1200, 2600, 150),
    RC(RC_TTM_STAR_02_MONKEY_CAGE,          RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_02,      RI_STAR,        2500, -1200, 1300),
    RC(RC_TTM_STAR_03_RED_COINS,            RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_03,      RI_STAR,        -3250, -2500, -3700),
    RC(RC_TTM_STAR_04_MOUNTAINSIDE,         RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_04,      RI_STAR,        -2900, -2700, 3650),
    RC(RC_TTM_STAR_05_BRIDGE_VIEW,          RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_05,      RI_STAR,        1800, 1200, 1050),
    RC(RC_TTM_STAR_06_MUSHROOM,             RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_06,      RI_STAR,        7300, -3100, 1300),
    RC(RC_TTM_STAR_07_100_COIN,             RCTYPE_COIN_RED,        LEVEL_TTM,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_VCUTM_RED_COIN_01,                RCTYPE_COIN_RED,        LEVEL_VCUTM,        RA_ACT_NONE,    RI_COIN_RED,    -5920, 4575, -4618),
    RC(RC_VCUTM_RED_COIN_02,                RCTYPE_COIN_RED,        LEVEL_VCUTM,        RA_ACT_NONE,    RI_COIN_RED,    -4740, 3581, -3854),
    RC(RC_VCUTM_RED_COIN_03,                RCTYPE_COIN_RED,        LEVEL_VCUTM,        RA_ACT_NONE,    RI_COIN_RED,    -4727, -227, -1161),
    RC(RC_VCUTM_RED_COIN_04,                RCTYPE_COIN_RED,        LEVEL_VCUTM,        RA_ACT_NONE,    RI_COIN_RED,    -3418, -559, -836),
    RC(RC_VCUTM_RED_COIN_05,                RCTYPE_COIN_RED,        LEVEL_VCUTM,        RA_ACT_NONE,    RI_COIN_RED,    -600, -1400, -6300),
    RC(RC_VCUTM_RED_COIN_06,                RCTYPE_COIN_RED,        LEVEL_VCUTM,        RA_ACT_NONE,    RI_COIN_RED,    900, -1400, -6300),
    RC(RC_VCUTM_RED_COIN_07,                RCTYPE_COIN_RED,        LEVEL_VCUTM,        RA_ACT_NONE,    RI_COIN_RED,    2750, -800, -6300),
    RC(RC_VCUTM_RED_COIN_08,                RCTYPE_COIN_RED,        LEVEL_VCUTM,        RA_ACT_NONE,    RI_COIN_RED,    4509, 0, -5527),
    RC(RC_VCUTM_STAR_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_VCUTM,        RA_ACT_01,      RI_STAR,        4600, 250, -4500),
    RC(RC_WDW_BLUE_COIN_01,                 RCTYPE_COIN_BLUE,       LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_BLUE,   1124, 400, -218),
    RC(RC_WDW_BLUE_COIN_02,                 RCTYPE_COIN_BLUE,       LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_BLUE,   1124, 400, 830),
    RC(RC_WDW_BLUE_COIN_03,                 RCTYPE_COIN_BLUE,       LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_BLUE,   832, 400, 1194),
    RC(RC_WDW_BLUE_COIN_04,                 RCTYPE_COIN_BLUE,       LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_BLUE,   1124, 400, 282),
    RC(RC_WDW_BLUE_COIN_05,                 RCTYPE_COIN_BLUE,       LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_BLUE,   420, 400, 1504),
    RC(RC_WDW_BLUE_COIN_06,                 RCTYPE_COIN_BLUE,       LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_BLUE,   -12, 400, 1808),
    RC(RC_WDW_RED_COIN_01,                  RCTYPE_COIN_RED,        LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_RED,    -3720, -1131, 520),
    RC(RC_WDW_RED_COIN_02,                  RCTYPE_COIN_RED,        LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_RED,    -2930, -850, 2560),
    RC(RC_WDW_RED_COIN_03,                  RCTYPE_COIN_RED,        LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_RED,    100, -1771, -1500),
    RC(RC_WDW_RED_COIN_04,                  RCTYPE_COIN_RED,        LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_RED,    1820, -1387, 1020),
    RC(RC_WDW_RED_COIN_05,                  RCTYPE_COIN_RED,        LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_RED,    -370, -1795, -180),
    RC(RC_WDW_RED_COIN_06,                  RCTYPE_COIN_RED,        LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_RED,    -1180, -1795, -180),
    RC(RC_WDW_RED_COIN_07,                  RCTYPE_COIN_RED,        LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_RED,    -780, -2155, 2860),
    RC(RC_WDW_RED_COIN_08,                  RCTYPE_COIN_RED,        LEVEL_WDW,          RA_ACT_NONE,    RI_COIN_RED,    -780, -1020, 3400),
    RC(RC_WDW_STAR_01_ARROW_LIFTS,          RCTYPE_STAR_DEFAULT,    LEVEL_WDW,          RA_ACT_01,      RI_STAR,        -2200, 2600, 3500),
    RC(RC_WDW_STAR_02_TOWN_TOP,             RCTYPE_STAR_DEFAULT,    LEVEL_WDW,          RA_ACT_02,      RI_STAR,        1550, 4350, 100),
    RC(RC_WDW_STAR_03_SECRETS,              RCTYPE_STAR_DEFAULT,    LEVEL_WDW,          RA_ACT_03,      RI_STAR,        3360, 1580, 2660),
    RC(RC_WDW_STAR_04_ELEVATOR,             RCTYPE_STAR_DEFAULT,    LEVEL_WDW,          RA_ACT_04,      RI_STAR,        890, 3400, -2040),
    RC(RC_WDW_STAR_05_RED_COINS,            RCTYPE_STAR_RED_COIN,   LEVEL_WDW,          RA_ACT_05,      RI_STAR,        -770, -1600, 3600),
    RC(RC_WDW_STAR_06_DOWNTOWN,             RCTYPE_STAR_DEFAULT,    LEVEL_WDW,          RA_ACT_06,      RI_STAR,        2180, -840, 3720),
    RC(RC_WDW_STAR_07_100_COIN,             RCTYPE_STAR_DEFAULT,    LEVEL_WDW,          RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_WF_BLUE_COIN_01,                  RCTYPE_COIN_BLUE,       LEVEL_WF,           RA_ACT_NONE,    RI_COIN_BLUE,   -2500, 450, -1150),
    RC(RC_WF_BLUE_COIN_02,                  RCTYPE_COIN_BLUE,       LEVEL_WF,           RA_ACT_NONE,    RI_COIN_BLUE,   -2500, 450, -900),
    RC(RC_WF_BLUE_COIN_03,                  RCTYPE_COIN_BLUE,       LEVEL_WF,           RA_ACT_NONE,    RI_COIN_BLUE,   -2500, 450, -650),
    RC(RC_WF_BLUE_COIN_04,                  RCTYPE_COIN_BLUE,       LEVEL_WF,           RA_ACT_NONE,    RI_COIN_BLUE,   -2500, 450, -1400),
    RC(RC_WF_RED_COIN_01,                   RCTYPE_COIN_RED,        LEVEL_WF,           RA_ACT_NONE,    RI_COIN_RED,    -250, 2650, 2970),
    RC(RC_WF_RED_COIN_02,                   RCTYPE_COIN_RED,        LEVEL_WF,           RA_ACT_NONE,    RI_COIN_RED,    1746, 3620, -3120),
    RC(RC_WF_RED_COIN_03,                   RCTYPE_COIN_RED,        LEVEL_WF,           RA_ACT_NONE,    RI_COIN_RED,    1277, 2600, 1350),
    RC(RC_WF_RED_COIN_04,                   RCTYPE_COIN_RED,        LEVEL_WF,           RA_ACT_NONE,    RI_COIN_RED,    1585, 2595, -80),
    RC(RC_WF_RED_COIN_05,                   RCTYPE_COIN_RED,        LEVEL_WF,           RA_ACT_NONE,    RI_COIN_RED,    3350, 3000, -1520),
    RC(RC_WF_RED_COIN_06,                   RCTYPE_COIN_RED,        LEVEL_WF,           RA_ACT_NONE,    RI_COIN_RED,    2700, 3600, -900),
    RC(RC_WF_RED_COIN_07,                   RCTYPE_COIN_RED,        LEVEL_WF,           RA_ACT_NONE,    RI_COIN_RED,    3770, 1380, 650),
    RC(RC_WF_RED_COIN_08,                   RCTYPE_COIN_RED,        LEVEL_WF,           RA_ACT_NONE,    RI_COIN_RED,    -270, 1720, 2250),
    RC(RC_WF_STAR_01_WHOMPS_BLOCK,          RCTYPE_STAR_DEFAULT,    LEVEL_WF,           RA_ACT_01,      RI_STAR,        180, 3880, 340),
    RC(RC_WF_STAR_02_FORTRESS_TOP,          RCTYPE_STAR_DEFAULT,    LEVEL_WF,           RA_ACT_02,      RI_STAR,        300, 5550, 0),
    RC(RC_WF_STAR_03_WILD_BLUE,             RCTYPE_STAR_DEFAULT,    LEVEL_WF,           RA_ACT_03,      RI_STAR,        -2500, 1500, -750),
    RC(RC_WF_STAR_04_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_WF,           RA_ACT_04,      RI_STAR,        4600, 550, 2500),
    RC(RC_WF_STAR_05_CAGED_ISLAND,          RCTYPE_STAR_DEFAULT,    LEVEL_WF,           RA_ACT_05,      RI_STAR,        2880, 4300, 190),
    RC(RC_WF_STAR_06_WALL,                  RCTYPE_STAR_DEFAULT,    LEVEL_WF,           RA_ACT_06,      RI_STAR,        590, 2450, 2650),
    RC(RC_WF_STAR_07_100_COIN,              RCTYPE_STAR_DEFAULT,    LEVEL_WF,           RA_ACT_COIN,    RI_STAR,        0, 0, 0),
    RC(RC_WMOTR_RED_COIN_01,                RCTYPE_COIN_RED,        LEVEL_WMOTR,        RA_ACT_NONE,    RI_COIN_RED,    -2980, 3990, -4248),
    RC(RC_WMOTR_RED_COIN_02,                RCTYPE_COIN_RED,        LEVEL_WMOTR,        RA_ACT_NONE,    RI_COIN_RED,    2735, 3140, -3085),
    RC(RC_WMOTR_RED_COIN_03,                RCTYPE_COIN_RED,        LEVEL_WMOTR,        RA_ACT_NONE,    RI_COIN_RED,    -3640, 4600, -4200),
    RC(RC_WMOTR_RED_COIN_04,                RCTYPE_COIN_RED,        LEVEL_WMOTR,        RA_ACT_NONE,    RI_COIN_RED,    4400, 240, 80),
    RC(RC_WMOTR_RED_COIN_05,                RCTYPE_COIN_RED,        LEVEL_WMOTR,        RA_ACT_NONE,    RI_COIN_RED,    3440, -2680, 5240),
    RC(RC_WMOTR_RED_COIN_06,                RCTYPE_COIN_RED,        LEVEL_WMOTR,        RA_ACT_NONE,    RI_COIN_RED,    -600, -1360, 5040),
    RC(RC_WMOTR_RED_COIN_07,                RCTYPE_COIN_RED,        LEVEL_WMOTR,        RA_ACT_NONE,    RI_COIN_RED,    320, 1725, 40),
    RC(RC_WMOTR_RED_COIN_08,                RCTYPE_COIN_RED,        LEVEL_WMOTR,        RA_ACT_NONE,    RI_COIN_RED,    -2560, 4600, -4800),
    RC(RC_WMOTR_STAR_RED_COINS,             RCTYPE_STAR_RED_COIN,   LEVEL_WMOTR,        RA_ACT_01,      RI_STAR,        -160, 1950, -470),
};
// clang-format on

RandoCheckId GetCheckByLocation(int16_t posX, int16_t posY, int16_t posZ) {
    for (auto& [randoCheckId, randoStaticCheck] : Rando::StaticData::Checks) {
        if (gCurrLevelNum != randoStaticCheck.levelId) {
            continue;
        }
        if (posX == randoStaticCheck.posX && posY == randoStaticCheck.posY && posZ == randoStaticCheck.posZ) {
            return randoCheckId;
        }
    }
    return RC_UNKNOWN;
}

RandoCheckId GetCheckByLevelAct(int16_t levelId, int16_t randoAct) {
    for (auto& [randoCheckId, randoStaticCheck] : Rando::StaticData::Checks) {
        if (gCurrLevelNum != randoStaticCheck.levelId) {
            continue;
        }
        if (randoAct == randoStaticCheck.actData) {
            return randoCheckId;
        }
    }
    return RC_UNKNOWN;
}

RandoStaticCheck GetShuffledRandoStaticCheck(s16 x, s16 y, s16 z) {
    RandoStaticCheck randoStaticCheck;
    RandoCheckId randoCheckId = Rando::StaticData::GetCheckByLocation(x, y, z);
    int16_t levelId = Rando::StaticData::Checks[randoCheckId].levelId;

    randoStaticCheck = Rando::StaticData::Checks[randoCheckId];
    randoStaticCheck.randoItemId = Rando::StaticData::GetShuffledRandoItem(randoCheckId);
    randoStaticCheck.actData = Rando::StaticData::GetShuffledRandoAct(randoCheckId);

    return randoStaticCheck;
}

} // namespace StaticData
} // namespace Rando
