name: MacOS Validation
on: [pull_request]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install MacPorts (if necessary)
        run: |
          if command -v /opt/local/bin/port 2>&1 >/dev/null; then
            echo "MacPorts already installed"
          else
            echo "Installing MacPorts"
            wget https://github.com/macports/macports-base/releases/download/v2.11.5/MacPorts-2.11.5-14-Sonoma.pkg
            sudo installer -pkg ./MacPorts-2.11.5-14-Sonoma.pkg -target /
          fi
          echo "/opt/local/bin:/opt/local/sbin" >> "$GITHUB_PATH"
      - name: Install dependencies (Universal)
        run: sudo port install libsdl2 libpng glew ninja cmake libzip nlohmann-json tinyxml2 spdlog vorbis-tools +universal
      - name: Build (Universal)
        run: |
          # CMAKE_OSX_ARCHITECTURES triggers the dual-architecture build
          cmake -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local -Dfmt_DIR=/opt/local/lib/libfmt10/cmake/fmt "-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64"
          cmake --build build-cmake -j
      - name: Create Package
        run: |
          mkdir ghostship-release
          mv build-cmake/Ghostship ghostship-release/
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ghostship-mac-universal
            path: ghostship-release
            retention-days: 1